In [1]:
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\bbc_data.csv")
df.head()

                                                data         labels
0  Musicians to tackle US red tape  Musicians gro...  entertainment
1  U2s desire to be number one  U2, who have won ...  entertainment
2  Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3  Snicket tops US box office chart  The film ada...  entertainment
4  Oceans Twelve raids box office  Oceans Twelve,...  entertainment

### EDA

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    2225 non-null   str
 1   labels  2225 non-null   str
dtypes: str(2)
memory usage: 34.9 KB

In [4]:
df.describe()

                                                     data labels
count                                                2225   2225
unique                                               2126      5
top     Oceans Twelve raids box office  Oceans Twelve,...  sport
freq                                                    2    511

In [5]:
df.shape

(2225, 2)

In [6]:
df.index

RangeIndex(start=0, stop=2225, step=1)

In [7]:
df.columns

Index(['data', 'labels'], dtype='str')

In [8]:
df.dtypes

data      str
labels    str
dtype: object

In [9]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
df.nunique()

### Data Cleaning