In [1]:
import pandas as pd
import numpy as np
import re
import string

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [3]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\tickets.zip")

## Basic EDA

In [4]:
df.shape

(8469, 17)

In [5]:
df.isna().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 1.1 MB

In [7]:
df.describe()

         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000

In [8]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8464    False
8465    False
8466    False
8467    False
8468    False
Length: 8469, dtype: bool

In [9]:
df.drop_duplicates()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8464,8465,David Todd,adam28@example.net,22,Female,LG OLED,2021-12-08,Product inquiry,Installation support,My {product_purchased} is making strange noise...,Open,NaN,Low,Phone,NaN,NaN,NaN
8465,8466,Lori Davis,russell68@example.com,27,Female,Bose SoundLink Speaker,2020-02-22,Technical issue,Refund request,I'm having an issue with the {product_purchase...,Open,NaN,Critical,Email,NaN,NaN,NaN
8466,8467,Michelle Kelley,ashley83@example.org,57,Female,GoPro Action Camera,2021-08-17,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,Eight account century nature kitchen.,High,Social media,2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,8468,Steven Rodriguez,fpowell@example.org,54,Male,PlayStation,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the {product_purchase...,Closed,We seat culture plan.,Medium,Email,2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,8469,Steven Davis MD,lori20@example.net,53,Other,Philips Hue Lights,2020-06-01,Billing inquiry,Hardware issue,There seems to be a hardware problem with my {...,Open,NaN,High,Phone,NaN,NaN,NaN

In [10]:
df.dropna(inplace=True)

In [11]:
df['text'] = df['Ticket Subject'] + " " + df['Ticket Description']

In [12]:
stop_words = set(stopwords.words('english'))#text cleaning
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+","",text)

    text = re.sub(r"[^a-zA-Z\s]"," ",text)

    words = word_tokenize(text)

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [13]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [30]:
df['text'] = (
    df['Ticket Subject'].fillna('') + ' ' +
    df['Ticket Description'].fillna('')
)

In [31]:
df['clean_text'] = df['text'].apply(clean_text)

In [32]:
print(df[['text','clean_text']].head())

                                                 text  \
2   Network problem I'm facing a problem with my {...
3   Account access I'm having an issue with the {p...
4   Data loss I'm having an issue with the {produc...
10  Data loss I'm having an issue with the {produc...
11  Software bug I'm having an issue with the {pro...

                                           clean_text
2   network problem facing problem product purchas...
3   account access issue product purchased please ...
4   data loss issue product purchased please assis...
10  data loss issue product purchased please assis...
11  software bug issue product purchased please as...

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    stop_words='english',
    min_df=2
)

X = tfidf.fit_transform(df['clean_text'])

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(df['Ticket Type'])

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [26]:
y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.21660649819494585

In [28]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print(cm)

[[16  7 10 29 47]
 [ 8  7 15 34 39]
 [14 11 18 37 27]
 [12 12 15 32 48]
 [ 9 11 12 37 47]]

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.27      0.15      0.19       109
           1       0.15      0.07      0.09       103
           2       0.26      0.17      0.20       107
           3       0.19      0.27      0.22       119
           4       0.23      0.41      0.29       116

    accuracy                           0.22       554
   macro avg       0.22      0.21      0.20       554
weighted avg       0.22      0.22      0.20       554

In [ ]:
new_ticket = ["My payment has been deducted twice but my order is not confirmed"]

new_ticket = [clean_text(new_ticket[0])]

new_vector = tfidf.transform(new_ticket)

prediction = model.predict(new_vector)

print("Predicted Ticket Type :", le.inverse_transform(prediction))

Predicted Ticket Type : ['Billing inquiry']

In [ ]:
print(df['Ticket Type'].value_counts())

Ticket Type
Refund request          596
Technical issue         580
Billing inquiry         544
Product inquiry         533
Cancellation request    516
Name: count, dtype: int64

In [ ]:
print(df['Ticket Type'].nunique())

5

In [ ]:
print(df['Ticket Type'].unique())

<StringArray>
[     'Technical issue',      'Billing inquiry', 'Cancellation request',
      'Product inquiry',       'Refund request']
Length: 5, dtype: str

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.23      0.13      0.17       109
           1       0.23      0.07      0.10       103
           2       0.25      0.17      0.20       107
           3       0.18      0.26      0.21       119
           4       0.22      0.41      0.28       116

    accuracy                           0.21       554
   macro avg       0.22      0.21      0.19       554
weighted avg       0.22      0.21      0.20       554

### Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

In [40]:
y_pred = model.predict(X_test)

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.19      0.19      0.19       109
           1       0.22      0.22      0.22       103
           2       0.27      0.22      0.24       107
           3       0.20      0.18      0.19       119
           4       0.28      0.35      0.31       116

    accuracy                           0.23       554
   macro avg       0.23      0.23      0.23       554
weighted avg       0.23      0.23      0.23       554

In [39]:
new_ticket = ["My payment has been deducted twice but my order is not confirmed"]

new_ticket = [clean_text(new_ticket[0])]

new_vector = tfidf.transform(new_ticket)

prediction = model.predict(new_vector)

print("Predicted Ticket Type :", le.inverse_transform(prediction))

Predicted Ticket Type : ['Technical issue']

In [37]:
y_pred = model.predict(X_test)

In [38]:
from sklearn.svm import LinearSVC

model = LinearSVC()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [43]:
new_ticket = ["My payment has been deducted twice but my order is not confirmed"]

new_ticket = [clean_text(new_ticket[0])]

new_vector = tfidf.transform(new_ticket)

prediction = model.predict(new_vector)

print("Predicted Ticket Type :", le.inverse_transform(prediction))

Predicted Ticket Type : ['Technical issue']

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.19      0.19      0.19       109
           1       0.22      0.22      0.22       103
           2       0.27      0.22      0.24       107
           3       0.20      0.18      0.19       119
           4       0.28      0.35      0.31       116

    accuracy                           0.23       554
   macro avg       0.23      0.23      0.23       554
weighted avg       0.23      0.23      0.23       554

### Objective

Customer support tickets ko automatically classify karna.

Dataset Challenges
Generic ticket templates
Repeated placeholders ({product_purchased})
Similar wording across multiple ticket types
Limited discriminative information in descriptions
1. Model Comparison
Naive Bayes :- fast hai aur baseline model ke liye useful hai.

Logistic Regression:-  text classification me often stronger results deta hai.

Linear SVC :- sparse TF-IDF features ke saath generally bahut achha perform karta hai.
Conclusion

2. Dataset ki text quality aur repeated templates ki wajah se perfect accuracy possible nahi thi. Isliye humne multiple models compare kiye aur sirf accuracy nahi, balki precision, recall aur F1-score ko bhi evaluate kiya.